apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rc
  labels:
    app: demo-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-rc
  template:
    metadata:
      labels:
        app: demo-rc
    spec:
      containers:
        - name: httpd
          image: httpd
          imagePullPolicy: Always

# kubectl get replicaset
# kubectl describe replicaset demo-rc
# kubectl delete replicaset demo-rc