apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    app: myweb

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
    app: myweb
  tmplate:
    ...

---
apiVersion: V1
kind: Service
metadata:
  name: myweb
spec:
  selector:
    app: myweb
  ports:
    - port: 8080

---
apiVersion: V1
kind: Deploment
metadata:
  name: myweb
spec:
  selector:
    matchLabels:
      app: myweb
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
      - {key: environment, operator: NorIn, values: [dev]}