apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-demo
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: app-demo
  targetCPUUtilizationPercentage: 90